- name: yum clean all
  shell: yum clean all
  args:
    warn: false
- shell: "! test -x /omd/sites/{{site}}/bin/set_admin_password || sudo su - {{ site }} -c 'set_admin_password omd'"
- shell: "omd config {{ site }} set TMPFS off"
